ESPIDF = /home/deets/software/vc/esp-idf
PORT = /dev/ttyUSB0
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
CROSS_COMPILE = xtensa-esp32-elf-
BUILD_VERBOSE=1
SRC_MOD += modnewjoy.c nj-mpu6050.c madgwick-ahrs.c
include Makefile

