ESPIDF = /Users/deets/software/vc/esp-idf
PORT = /dev/ttyUSB0
#FLASH_MODE = qio
#FLASH_SIZE = 4MB
CROSS_COMPILE = xtensa-esp32-elf-
BUILD_VERBOSE=1
SRC_MOD += modnewjoy.c nj-mpu6050.c madgwick-ahrs.c nj-bmp280.c nj-i2c.c nj-nrf24.c
include Makefile

